# Generated by Django 4.2.30 on 2026-06-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_interviewsession_delete_interviewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='ques_type',
            field=models.CharField(choices=[('qa', 'Questions & Answers'), ('mcq', 'MCQ')], default='qa', max_length=10),
        ),
    ]
